# Secrets에 저장한 값:
# EC2_HOST = 13.125.92.241
# EC2_USERNAME = ubuntu
# EC2_KEY = (pem 파일 내용)

name: Deploy to EC2 # workflow 의 이름

on: # trigger
  push:
    branches: [main] # main 브랜치에 push될 때 자동 실행

jobs: # job 은 1개 이상의 job 으로 구성됨. job 이 여러개인경우 병렬구조로 동작된다.
  deploy: # 이 부분의 이름은 내 마음대로. job 의 고유 id 라고 생각하면 됨
    # github 에서 레포지토리 -> actions 탭 들어가면 표시되는 이름
    runs-on: ubuntu-latest # GitHub이 제공하는 가상 컴퓨터에서 실행

    steps:
      - name: EC2 접속
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }} # → 13.125.92.241
          username: ${{ secrets.EC2_USERNAME }} # → ubuntu
          key: ${{ secrets.EC2_KEY }} # → pem 내용

          script: | # 실제 코드 수정하는 부분
            cd ~/board-app-github-actions-v1
            docker compose pull
            docker compose up -d
            docker image prune -f

#######################################################
##########  이건 보험임. 일단 안해도 됨 #############
# script: |    # 실제 코드 수정하는 부분
#   cd ~/board-app-github-actions-v1
#   git pull origin main
#   docker compose down
#   docker compose build --no-cache
#   docker compose up -d
#   docker image prune -f
